### ISSUE TITLE
Command-line usage

### ISSUE THREAD

**Issue by minexew** [Col-E/JRemapper#21]
Hi, is there any way to use the tool in a batch mode, without a GUI, just supplying a list of operations in a file?

If not, what would it take to implement?

Thanks.

**Comment by Col-E** [comment]
While JRemapper doesn't have command line usage, [Recaf's 2.0 redesign does](https://github.com/Col-E/Recaf/tree/redesign):
![image](https://user-images.githubusercontent.com/21371686/79050980-95e45b80-7bfb-11ea-8be7-6c0671454bd7.png)

Also if you don't want to script around Recaf externally you can provide a text file that contains Recaf internal commands like so: 

```
loadworkspace <file-name>
remap <mapping-type> <other-options> <mapping-file>
export <output-file>
```
Then call Recaf with `java -jar recaf.jar --cli --script MyScript.txt`

**Comment by Col-E** [comment]
Also, I am not actively working on this project for the time being. I'd recommend [FabricMC/Enigma](https://github.com/FabricMC/Enigma)

Recaf supports its mapping type if you want to use the command-line usage above.

**Comment by minexew** [comment]
Awesome! I'll check out Recaf, sounds very promising.
